### ISSUE TITLE
config path for .yaml file

### ISSUE THREAD

**Issue by matallo** [contentful/jekyll-contentful-data-import#1]
it would be great to define in the `jekyll contentful` command a variable with the path where the `.yaml` will be generated, or use the `_config.yml` for that

I have the next line in my Jekyll config:
```
source: '_app'
```

so, after running the command I need to copy the resulting file

**Comment by dlitvakb** [comment]
Hey @matallo,

That sounds like a good idea

I'll add this to my backlog and get back to you as soon as I can

Cheers

**Comment by dlitvakb** [comment]
Hey @matallo,

I've created a PR with this issue addressed.

I'll get it merged as soon as possible

Cheers

**Comment by matallo** [comment]
BOOM, awesome

**Comment by dlitvakb** [comment]
@matallo released as `v1.2.0` :smile:
