### ISSUE TITLE
Error Pulling In Data

### ISSUE THREAD

**Issue by mattonomics** [contentful/jekyll-contentful-data-import#12]
I'm new to Jekyll and Contentful, so hang with me as I figure this out :)

I'm running a new install of Jekyll 3.1.6 locally and when running `jekyll contentful` I'm getting the following error:
`/Library/Ruby/Gems/2.0.0/gems/jekyll-contentful-data-import-1.2.1/lib/jekyll-contentful-data-import/mappers/base.rb:82: stack level too deep (SystemStackError)`

I'd really appreciate any help/advice on getting this error resolved. Thank you!

**Comment by dlitvakb** [comment]
Hey @mattonomics,

This happens when you have circular references in your Content Types.

Try to remove the fields that are causing the circular reference and that should solve the issue.

Hope that helps

**Comment by mattonomics** [comment]
@dlitvakb Upfront apology again for my ignorance, but I'm not sure what you mean. It's not 100% clear to me what I can show you that would be helpful, but here's what I _added_ to the `_config.yml` file:
```ruby
# Contentful Settings

contentful:
  spaces:
    - post:
        space: 111 # the real space id is here
        access_token: 111 # the real token is here
```
The entire contents of my Gemfile is
```ruby
source 'https://rubygems.org'

group :jekyll_plugins do
  gem "jekyll-contentful-data-import"
end
```
In my Contentful instance I'm using the pre-populated example content (Author, Cat videos, Category, Post).

I hope that this is helpful for you to guide me on fixing. I'm _extremely_ grateful that you've made yourself available to assist!!

**Comment by dlitvakb** [comment]
Hey @mattonomics,

If you go to the Contentful Web App, enter your space, and go to Content Types -> Author, there is a reference field called `Created entries`, disable that field.

After that, everything should work again.

This issue is being caused by having a circular reference in your Content Model

Hope this helps

Cheers
