### ISSUE TITLE
Reverse of this?

### ISSUE THREAD

**Issue by mrh-is** [contentful/jekyll-contentful-data-import#13]
Is there a way to reverse this process and put data into Contentful from YAML files? I have an existing Jekyll blog I want to migrate to Contentful.

**Comment by dlitvakb** [comment]
Hey @mrh-is,

You could transform your YAML files to JSON and use https://github.com/contentful/contentful-bootstrap.rb#json-templates

The format is pretty straight forward and conversion should be pretty simple.

Hope that helps

**Comment by dlitvakb** [comment]
Hey @mrh-is,

I'm closing this issue as there has been no response lately.

Hope you could solve it with the solution I provided.

Cheers

**Comment by mrh-is** [comment]
Indeed I did! Thanks for all the help.
