### ISSUE TITLE
Markdown not parsed well

### ISSUE THREAD

**Issue by theobouwman** [contentful/jekyll-contentful-data-import#17]
Hello other Jekyll programmers,

I have a problem with contentful giving me Markdown as response (which is not a problem). But when I loop through the data and print the 'body"-field which is markdown Jekyll actually prints the raw data.

---
title: Blog
permalink: /blog
---

<h1 class="page-heading">Blog Posts</h1>

<ul class="post-list">
  {% for post in site.data.contentful.spaces.site.blog-post %}
    <li>
      <p>{{ post.body }}</p>
    </li>
  {% endfor %}
</ul>

<p class="rss-subscribe">subscribe <a href="{{ "/feed.xml" | prepend: site.baseurl }}">via RSS</a></p>`

this will give me the following html:

`<ul class="post-list">
  
    <li>
      <p>__Hello everyone,__

yesterday was a beautiful day in Amsterdam @ straf_werk festival 2016.

At first there was a littlebit rain, but then the sun came through and the sphere was nice.

We've danced a lot and where back in Soest around 1 a.m.

Theo.</p>
    </li>
  
    <li>
      <p>__Test Blog Post__

just a lovely day in Berlin @ the bar.

See you tomorrow.

1. first
2. second
3. third
4. fourth
5. fifth
6. sixth

[Community platform](http://community.now)
</p>
    </li>
  
</ul>
`

I hope someone could help me with this.

Theo

**Comment by dlitvakb** [comment]
Hey @theobouwman,

You need to add the markdown filter.

From [Jekyll Templates page](https://jekyllrb.com/docs/templates/):

Markdownify
Convert a Markdown-formatted string into HTML.
```liquid
{{ page.excerpt | markdownify }}
```

**Comment by theobouwman** [comment]
Thanks, did the trick.
