### ISSUE TITLE
Error importing

### ISSUE THREAD

**Issue by rossfishkind** [contentful/jekyll-contentful-data-import#20]
Hey there!

I installed the modules and set up my `_config.yml` file. Everything seems to look good there, but when I run `jekyll contentful`, I receive the following error:

```
Starting Contentful import
jekyll 3.2.1 | Error:  The resource could not be found.
```

Let me know if you need me to provide any additional info. Thanks again!

**Comment by rossfishkind** [comment]
I found the problem - I was just being really stupid. My production key was wrong.

**Comment by dlitvakb** [comment]
Hey! Glad you could solve it! Sorry I just read this, took the day off sick.

Cheers
