### ISSUE TITLE
Require mappers automatically

### ISSUE THREAD

**Issue by jcbpl** [contentful/jekyll-contentful-data-import#22]
It'd be great to be able to use custom mappers without also needing to switch from the `jekyll contentful` command to a Rake task; is there any reason not to automatically require mappers from the _plugins directory?

Following the example of [`Jekyll::PluginManager`](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/plugin_manager.rb), it seems it could be as simple as this:

```ruby
def require_mappers(config)
  mapper_search_path = File.join(config["source"], config["plugins_dir"], "mappers")
  mapper_files = Jekyll::Utils.safe_glob(mapper_search_path, File.join("**", "*.rb"))
  Jekyll::External.require_with_graceful_fail(mapper_files)
end
```

This uses the `source` and `plugins_dir` values returned by `Jekyll.configuration` in the [command file](https://github.com/contentful/jekyll-contentful-data-import/blob/master/lib/jekyll/commands/contentful.rb#L14), so one option is to put this code there, but I imagine it might be better to put it in the `Base` mapper, next to `mapper_for`. The only catch is that would require some minor refactoring to `Importer`, since it currently expects only the `contentful` key of `Jekyll.configuration`.

Let me know what you think! I'd be glad to submit a PR.

**Comment by dlitvakb** [comment]
This sounds like a good thing to do 😄 

Would you like to do it yourself?
