### ISSUE TITLE
Locales option

### ISSUE THREAD

**Issue by designbysoil** [contentful/jekyll-contentful-data-import#29]
How can you import content with different locales?

**Comment by dlitvakb** [comment]
Hey @designbysoil,

Found an issue with the gem, fixing and pushing right now. The gem was trying to pull the option as `:locale` instead of `'locale'`.

The way to use locales is by adding the `locale: 'your_locale_code'` or `locale: '*'` option in the `cda_query:` option block in the configuration file.

Will get this fix in a few minutes.

Cheers

**Comment by designbysoil** [comment]
Thanks @dlitvakb looking forward to the fix.

**Comment by dlitvakb** [comment]
Hey @designbysoil,

Version 1.4.0 was just released fixing the issue with `locale: '*'`

Cheers

**Comment by designbysoil** [comment]
Thanks @dlitvakb!

**Comment by designbysoil** [comment]
Noticed that with `locale: '*'` the images data has missing keys like title and url.

Without setting the locale option or with a single locale set as `locale: 'en-US'`
`image:
    title: 'Photo of the event'
    url: "//images.contentful.com/abc/abc/abc/event.jpg”`

With `locale: '*'`
`image:
    en-US:
      sys:
        type: Link
        linkType: Asset
        id: xxxx`

Only the sys key comes through the title, url etc. are missing.

**Comment by dlitvakb** [comment]
Hey @designbysoil,

This has been found and solved, you can follow #31 for progress, I will make a patch release after that's merged.

Cheers

**Comment by designbysoil** [comment]
Hey @dlitvakb,

Encountered another issue with locale data of images. When an entry is imported the linked image data of the additional locale is only showing `image.ar-QA.sys.id`. Other keys are missing:

⚠️  image.ar-QA.title
⚠️  image.ar-QA.url

See screenshot:
http://dl.dropbox.com/u/450152/localised-image-date-events_yaml.png

Can the `title` and `url` of the localised image be added to the image data?

**Comment by dlitvakb** [comment]
Hey @designbysoil,

I'll take a look at it again on Monday

Cheers

PS: Reopening

**Comment by dlitvakb** [comment]
Hey @designbysoil,

Can you open a support ticket and request for me?

Please include the space credentials in the ticket so I can check for you specific issue.

I'm testing with the space you provided me last time for fixing this issue, and there is no localized content with issues.

Cheers

**Comment by designbysoil** [comment]
Hey @dlitvakb,

There is a ticket #13319. I have specified the asset I am trying to get the localised image data of. 

Thanks,
