### ISSUE TITLE
Blank draft copies will error out preview imports

### ISSUE THREAD

**Issue by tmartin2089** [contentful/jekyll-contentful-data-import#33]
Getting the following error:

jekyll 3.3.0 | Error:  undefined method `each' for nil:NilClass

As near as I can figure, any new records that are left empty will cause this import error.   Contentful auto-saves drafts so its not hard to generate a blank record here and there.

Otherwise, I love this Gem.  Great job contentful team!

**Comment by dlitvakb** [comment]
Hey @tmartin2089,

I'll be checking on this.

Cheers

**Comment by dlitvakb** [comment]
Hey @tmartin2089,

Could you create a support request asking for me and including:

* Space ID
* Delivery Access Token
* Preview Access Token

This way I can check what your problem in particular is, as I cannot reproduce myself.

Cheers
