### ISSUE TITLE
'for' tag was never closed in /_layouts/home.html

### ISSUE THREAD

**Issue by kapena** [contentful/jekyll-contentful-data-import#40]
When running `jekyll serve` i get the following.
` Liquid Exception: Liquid syntax error (line 4): 'for' tag was never closed in /_layouts/home.html` 

I'm not sure how the `for` tag isn't closed when clearly it appears to be closed here

```html 
---
layout: default
---
<!-- Posts -->
<div class="jumbotron">
  <div class="container">
         {% for link in site.data.contentful.spaces.links.link %}
        <dt id="postPadd" class="list-group-item">
            <h1 id="t-pad">
              <a class="post-link text-primary" href="{{ link.url | relative_url }}">{{ link.title | escape }}</a>
            </h1>
            <div class="container">
              <span class="post-meta">Published <mark>{{ link.date | date: "%b %-d, %Y" }}</mark></span>
                <p class="rss-subscribe"><a href="{{ "/feed.xml" | relative_url }}">Subscribe</a></p>
                <div class="col-sm-8 col-med-8">
                    <img id="img-pad" class="img-fluid img" src="{{ site.baseurl }}assets/{{ link.image }}" />
                    <h5 id="exc-pad">{{ post.excerpt }}</h5>
                    <a id="btn-marg" href="{{ link.url | relative_url }}" class="btn btn-info btn-md active" role="button" aria-pressed="true">Read Now</a>
                </div>
            </div>  
        </dt>
          {% endfor %}
     </div>
</div>
```

Is there something that I am missing ?

**Comment by kapena** [comment]
I'm thinking it has something to do with the variables in the `for`.  My contentful directory  is inside the _data  directory

**Comment by dlitvakb** [comment]
Hey @kapena,

I'm not entirely sure what the issue is here, I'm not a Liquid template expert sadly.

For what I can see everything there looks correct and nothing Contentful related is wrong.

I'd try to ask in the Jekyll IRC or Slack communities and see if you can get a better answer there.

I'm really sorry I cannot be of more help.

Cheers
