### ISSUE TITLE
Missing entries in the imported yaml file

### ISSUE THREAD

**Issue by designbysoil** [contentful/jekyll-contentful-data-import#41]
Any ideas why the yaml file would sometimes include an entry and later on randomly not include that same entry on subsequent imports.

We are experiencing this issue very regularly now. We have around 133 entries on Contentful that are published but not all of them are showing up in resulting yaml file. But if I go and make the missing entry Draft and then publish it again. It shows up in the yaml file.

Would really appreciate any help with this issue.

**Comment by designbysoil** [comment]
Ahh, great. Forgot about the default limit!

**Comment by designbysoil** [comment]
Does this import maximum 1000 entries or imports everything?

**Comment by dlitvakb** [comment]
By using `all_entries` the gem automatically goes through every page in your content if you have over 1000 entries, you can also set the maximum size of each page in the config.

Cheers
