### ISSUE TITLE
Individual posts not being created

### ISSUE THREAD

**Issue by travis-zookacreative** [contentful/jekyll-contentful-data-import#47]
Hey there! Not sure what I am missing but its clearly something! I have `individual_entry_files: true` in my config.yml file and I am able to successfully import data into the data directory however from there nothing happens. I can loop the data but I need physical files created for each post in the data yml file. Is there something more needed? Thanks!

**Comment by dlitvakb** [comment]
Hey @travis-zookacreative,

Can you explain me better the issue? If you're able to loop through the data, that means that the data is, in fact, there.

Please check in your `_data` directory (or if overridden, the place which it would be located), that the sub directories have been created. By default it should have the path `_data/contentful/spaces/{space_alias}/{content_type_id}/{entry_id}.yaml` when using the individual entry files option, else it will be `_data/contentful/spaces/{space_alias}.yaml`.

Cheers

**Comment by travis-zookacreative** [comment]
My data _is_ there, the solution I'm looking for though is to on build create a single post for each item in the yaml file. Currently I am able to loop through the data but that only lists out the data. Is there an add on or additional settings to create individual post files and be able to link to them on build?

**Comment by dlitvakb** [comment]
Hey @travis-zookacreative,

The benefit is that allows you to work with a plugin like https://github.com/avillafiorita/jekyll-datapage_gen, which allows you to build a single page per file.

Cheers

**Comment by travis-zookacreative** [comment]
I tried that plugin before commenting but always got the error `Error:  no implicit conversion of String into Integer`. Do you have any examples of this plugin working with contentful yaml data?

**Comment by dlitvakb** [comment]
Hey @travis-zookacreative,

I haven't used it myself, but I've known of many people successfully using it and they've been requesting this specific feature for that specific purpose.

Sadly, I cannot address questions out of the scope of this plugin itself, as I'm not an expert in other plugins.

My advise would be to tweak the settings and try different possibilities, or use a different page generator plugin, I know of at least another one being available, don't remember the url though.

Cheers

**Comment by travis-zookacreative** [comment]
No worries, I'll work it out. Thanks for the insight!
