### ISSUE TITLE
How to handle blog posts

### ISSUE THREAD

**Issue by designbysoil** [contentful/jekyll-contentful-data-import#48]
Is it possible to generate individual posts with the filename in `YEAR-MONTH-DAY-title.MARKUP` format?

I understand that now we can generate individual files but I don't see an option for specifying the format of the filename and choosing the destination outside of data folder. With this last missing piece, I think we would be able to use contentful data to generate blog posts. 

If it is not the suggested approach than how are people handling blog posts with contentful data?

**Comment by dlitvakb** [comment]
Hey @designbysoil,

I've answered through support channels, we'll continue through there. Closing this issue.

Cheers

**Comment by leoschweizer** [comment]
Wondering the same. What is the answer to this?
