### ISSUE TITLE
Individual posts not showing up in data folder

### ISSUE THREAD

**Issue by coreycondardo** [contentful/jekyll-contentful-data-import#49]
I set `individual_entry_files` to true, and ran `jekyll contentful --rebuild` but I still only have a single yaml file in my spaces directory. Is there some other step that I am missing?

**Comment by dlitvakb** [comment]
Hey @coreycondardo,

Which version of the gem are you running?

Cheers

**Comment by coreycondardo** [comment]
@dlitvakb From my Gemfile.lock
```
    jekyll-contentful-data-import (1.5.1)
      contentful (~> 2.0, >= 2.0.1)
```

**Comment by dlitvakb** [comment]
Hey @coreycondardo,

The individual file per entry feature is not yet released and only available on `master`.

Please update to use the `master` branch or wait for next release. Which should be coming either tomorrow or early next week.

Cheers

**Comment by coreycondardo** [comment]
Ah that explains it! Thank you.
