### ISSUE TITLE
Import date says tomorrow

### ISSUE THREAD

**Issue by coreycondardo** [contentful/jekyll-contentful-data-import#51]
A post I wrote ~11PM EST was imported as the next day ~3AM.

Is there a setting I'm missing to tweak this to import at my current timezone?

~Corey

**Comment by dlitvakb** [comment]
Hey @coreycondardo,

Have you checked what timezone is selected in your entry inside Contentful? The importer just fetches what's sent from the API, keeping TZ information.

Cheers
