### ISSUE TITLE
Slow Contentful Import

### ISSUE THREAD

**Issue by skully78** [contentful/jekyll-contentful-data-import#53]
I have noticed since the last 4 days ago our Jekyll Contentful imports are taking extremely long.
On Netlify build servers and locally. 

- Using contentful 2.1.3
- Using jekyll-contentful-data-import 1.6.0
- Starting Contentful import
- Killed
- Finished 'contentfulDump' after 5.95 min

**Comment by dlitvakb** [comment]
Hey @skully78,

Can you try downgrading to 2.1.2 and let me know if the upgrade is what's causing the slow-down?

Also please re-run on 2.1.3 to make sure that this isn't an isolated case.

Please post the results here when you're done.

Cheers

**Comment by skully78** [comment]
Hi @dlitvakb

I downgraded to contenful 2.1.2. Confirmed installed gems. Still takes over 5 mins to generate the data file.

I have a copy of the build logs from Netlify.
The only gems which differ are faraday and algolia search.

On the left, contentful import took 1.63s. Aug 18 at 4:10 pm
On the right import was killed. Aug 21 at 12:38 pm
http://www.mergely.com/fIQowGfF/

**Comment by dlitvakb** [comment]
Hey @skully78,

This looks to be unrelated to the gem itself, can you open a support request at https://support.contentful.com/hc/en-us explaining your issue and providing any possible information you think that may be useful.

That way our support engineers can report the issue to the corresponding people to investigate your issue further, but as far as I can tell, there's no change that could have affected performance on the ruby side of things.

Hope your issue gets resolved soon,

Cheers

**Comment by skully78** [comment]
Hello, 

Something must have been changed on the Contenful side, as imports are back to expected speed.

Good times.
