### ISSUE TITLE
Retrieving assets?

### ISSUE THREAD

**Issue by stephthedev** [contentful/jekyll-contentful-data-import#58]
Is it possible to retrieve all assets in a space? I can't seem to find an example indicating how to do that.

Thanks!

**Comment by dlitvakb** [comment]
Hey @stephthedev,

With the current state of the gem, it's only possible to retrieve assets that are linked to entries.

If you provide me with more details, maybe we can see if there's a way to work around your issue, or if we need to add functionality to retrieve all assets as an optional behaviour.

Cheers

**Comment by stephthedev** [comment]
Howdy!

I'm looking to retrieve a list of all assets in a space as a jekyll data yaml file. Then, I'd like to loop through the data file and generate an image tag using its thumbnail (via the image api) and also include a link to the image for further viewing. 

I know I can use the [contentful.rb ](https://github.com/contentful/contentful.rb) api, but the jekyll-contentful-data-import api would save me a step by avoiding creating the yaml file on my end. 

Thanks again :-)

p.s. The jekyll-contentful-data-import api is fantastic!

**Comment by dlitvakb** [comment]
Hey @stephthedev,

This looks definitely something that is not possible at the moment with this tool.

I'll add it to my feature backlog, sadly, I cannot promise it will get implemented any time soon, as I'm about to have a baby and I have parental leave until February.

But I'll try to add it before that time, if this happens, I'll let you know.

If you're willing to help implementing it, it would be awesome.

Cheers

**Comment by dlitvakb** [comment]
Please look at the comment above ☝️ 

Cheers

**Comment by stephthedev** [comment]
Hey @dlitvakb 

First things first, congrats on the new baby! Hope the baby is happy and healthy!

I've actually figured out a (cheap) [workaround](https://github.com/lindsphotography/lindsphotography.github.io/blob/sortiz/blogging/Rakefile#L36) using the contentful.rb gem. So far I only have 1 asset, so I'm not sure how well this will perform when I have about 50+ or so. There's some amount of hard-coding, but it works for now. 

Your idea sounds like another viable workaround. Unfortunately, not all of my assets will be tied to content (this might change in the future). Right now, I'm using Contentful as a:
* CMS - for adding blog posts
* CDN - for showcasing Editor created photographs; for powerful on-the-fly image processing

Regardless, thanks for the speedy replies and brainstorming with me. 
Good luck with the baby!

**Comment by dlitvakb** [comment]
Hey @stephthedev,

That's a WAY simpler workaround than mine 😅 !

Thanks for the good wishes!

Cheers
