### ISSUE TITLE
jekyll contentful data import issue 

### ISSUE THREAD

**Issue by KochuraniT** [contentful/jekyll-contentful-data-import#59]
i got the error jekyll 3.7.0 | Error: undefined method `gsub' for #Hash:0x000000058f0318 on rake build command, and the following is my _config.yml file contents:
[_config.txt](https://github.com/contentful/jekyll-contentful-data-import/files/1662736/_config.txt)

**Comment by dlitvakb** [comment]
Hey @KochuraniT,

I cannot reproduce that issue, I'm only getting an error that the `gallery` content type does not exist.

Cheers
