### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by andreirt** [contentful/jekyll-contentful-data-import#61]
It looks like environment variables can be used in my_website field, but not in client_options fields. So it's needed to use two config files to be able to change the environment (like master/staging). It can be done, but it would be great if it was possible to use a single config file, plus environment variables to achieve this.

- my_website: 
        space: ENV_CONTENTFUL_SPACE_ID         
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN 
        client_options:
            environment: staging
            space: ENV_CONTENTFUL_SPACE_ID
            access_token: ENV_CONTENTFUL_ACCESS_TOKEN

**Comment by dlitvakb** [comment]
Hey @andreirt,

This would be a cool feature to add.

Currently I'm on parental leave and starting to work again next month.

I'll make sure to add this to my backlog and add the feature when I'm back.

Cheers

**Comment by dlitvakb** [comment]
Hey @andreirt,

I'm tackling this issue now, will let you know when it's released.

Cheers

**Comment by dlitvakb** [comment]
Hey @andreirt,

Release `1.7.0` with this feature was just released.

Cheers
