### ISSUE TITLE
Enable this gem for Github Pages

### ISSUE THREAD

**Issue by paesku** [contentful/jekyll-contentful-data-import#7]
Hi,

I really love your Service and the Jekyll integration. What I miss is using this plugin on GitHub for creating my Site. As far as I understood  [GitHub](https://help.github.com/articles/configuring-jekyll-plugins/) has to add this to their plugins whitelist. Is there a workaround?

**Comment by ivanoats** [comment]
Paesku -would running it locally wok for you? Or building on a CI service such as Wercker.com ?

**Comment by paesku** [comment]
@ivanoats Thank you for the tip. I will give it a try. But isn't it just another (unnecessary) step in the process? I have this idea in mind that the customer creates his data, the developer creates the templates with a static site generator and it all becomes live on github.

**Comment by dlitvakb** [comment]
Hey @paesku, @ivanoats,

Sadly GitHub Pages only allows 1st party Jekyll plugins, and it's a very very short list of 4 plugins total.

The way I've been using it myself, is to locally pull content from Contentful, and then have the static site published on the gh-pages branch. A similar and better documented approach can be found here: http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html.

@ivanoats gave also a nice solution, using a CI service, you could on commit, have `jekyll contentful` run, then do the steps listed in the link above to push to your Pages site.

This is even possible on Travis CI without much trouble.

I'll write a tutorial about it soon,

Cheers

**Comment by ivanoats** [comment]
Stay tuned for an announcement from us at http://www.aerboatic.com ;-)

**Comment by paesku** [comment]
After fiddling with wercker I made it all run together. My solution triggers wercker on master and pushes only the build content within _site and the help of [leipert/step-git-push](https://github.com/leipert/step-git-push) to the gh-pages branch on github. Thank you guys!
Anyhow, @ivanoats  your article looks very interesting.
