### ISSUE TITLE
Update gemspec dependancy for rich_text_renderer

### ISSUE THREAD

**Issue by katokalen** [contentful/jekyll-contentful-data-import#70]
Hi there,

rich_text_renderer is now on version 0.2: https://github.com/contentful/rich-text-renderer.rb/releases

Looks like it's still pointing to 0.1 in the gemspec file.

**Comment by dlitvakb** [comment]
Hey @katokalen,

The gemspec specifies that the `rich_text_renderer` gem is `at least` version `0.1`, if any newer version is found it will be installed.

Cheers
