### ISSUE TITLE
Is it possible to use includes for rich-text content types?

### ISSUE THREAD

**Issue by daimz** [contentful/jekyll-contentful-data-import#73]
I have a bunch of components that I am using includes for through out my site, however I'm porting over the blog to contentful and it uses some of these blocks. Rather than duplicate the code I'd prefer to use includes with in the renderer something like this:
```
class EntryBlockRenderer < RichTextRenderer::BaseNodeRenderer
  def render(node)
    
    entry = node['data']['target']
    sys = entry['sys']
    content_type = sys['content_type_id']
   
    if content_type == 'media'
      "{% include components/media-item.html title=#{entry['title']}  link=#{entry['link']} date=#{entry['publish_date']}  %}"
    elsif content_type == 'codeBlock'
      "{% include components/code.html code="<p>test</p>" lang="html" %}"
    else
       "<div>#{content_type_id}</div>"
    end
  end
end
```

Currently this just renders the includes as a string `{% include components/media-item.html title=#{entry['title']}  link=#{entry['link']} date=#{entry['publish_date']}  %}` rather than the actual include code.

Is it possible to do this?

**Comment by dlitvakb** [comment]
Hey @daimz,

While I don't think it's possible doing it exactly the way you're proposing, I could imagine that it is possible to programatically invoke the rendering of the partial template, something along the lines of:

```ruby
template = Liquid::Template.parse(File.read('path/to/your/partial'))
template.render(whatever: 'thing', you: 'want', to: 'pass')
```

While maybe not as easy as just using the `include` statement, it should be equivalent in result.

I haven't tested this personally, but from reading Liquid and Jekyll docs, it seems that this would be the best way to replicate your desired behaviour.

Hope this helps,

Cheers

**Comment by daimz** [comment]
Thanks for that @dlitvakb, Looks like it worked perfectly!

Appreciate the help.
