### ISSUE TITLE
Not importing drafts

### ISSUE THREAD

**Issue by alejorivera** [contentful/jekyll-contentful-data-import#75]
Even though I'm using the Content Preview API access token.

**Comment by dlitvakb** [comment]
Hey @alejorivera,

Have you made sure that on the `client_options` section of the configuration, you've set up `api_url: preview.contentful.com`?

You can find more information on the configuration options here: https://github.com/contentful/jekyll-contentful-data-import#configuration

Hope this helps,

Cheers

**Comment by alejorivera** [comment]
Yep, that was the issue. Thank you! 🙌 

PS: Not clear what the Content Preview API access token is for then, maybe y'all at Contentful could make that clear in the documentation.
