### ISSUE TITLE
Support for Jekyll 4.0.0

### ISSUE THREAD

**Issue by remotesynth** [contentful/jekyll-contentful-data-import#76]
I was trying to test this but, unless I am mistaken, it appears that it isn't compatible with the recent Jekyll 4.0.0 release yet.

**Comment by denisw** [comment]
Possibly, all that's needed is to change the gemspec from saying:

```ruby
s.add_dependency("jekyll", ">= 2.5.0", "< 4")
```

to:

```ruby
s.add_dependency("jekyll", ">= 2.5.0", "< 5")
```

**Comment by daimz** [comment]
It it possible to support Jekyll 4.0.0 yet?

**Comment by darkkatarsis** [comment]
Im also waiting

**Comment by iamalfonse** [comment]
Still waiting here also
